apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-lab-api
  namespace: derek-local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-lab-api
  template:
    metadata:
      labels:
        app: dotnet-lab-api
    spec:
      containers:
        - name: dotnet-lab-api
          image: localhost/dotnet-webapi:latest   # 你本地构建的镜像名
          imagePullPolicy: IfNotPresent # 优先用本地镜像
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development